# Default values for notes-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  activeProfile: dev
  name: notes-service
  mainPort: 9004
  managementPort: 9192
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 768Mi
      cpu: 500m
  loggingLevelApp: DEBUG
  loggingLevelSpring: DEBUG
  db:
    datasourceHost: postgres-service
    datasourceDbName: notes-service
  minReplicas: 1
  maxReplicas: 3


image:
  repository: andreyjava404/notes-service
  tag: 4.0.2-b693387
  imagePullPolicy: Always

hpa:
  cpuUtilization: 70
  scaleDown:
    stabilizationWindowSeconds: 300
  scaleUp:
    stabilizationWindowSeconds: 0