spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  application:
    name: service-notes
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: jdbc:postgresql://${DATASOURCE_HOST}:5432/${DATASOURCE_DBNAME}
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 9004
  servlet:
    context-path: /service-notes

management:
  observations:
    http:
      server:
        requests:
          filter:
            pattern: "/actuator/**" #disable actuator tracing
            enabled: false
    enable:
      spring:
        security: false #disable security tracing
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://zipkin-service.notes-app.svc.cluster.local:9411/api/v2/spans
  server:
    port: 9192
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers, monitoring, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    com.saveit: ${LOGGING_LEVEL_APP:ERROR}
    org.springframework: ${LOGGING_LEVEL_SPRING:ERROR}