spring:
  datasource:
    username: db_notes_service_test_usr
    password: my_secret_pwd_notes_service
    url: jdbc:postgresql://localhost:5432/notes-service

server:
  port: 9000

logging:
  level:
    com.saveit: DEBUG
    org.springframework: DEBUG
