apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-service-config
  namespace: notes-app
data:
  # --- notes-service ---
  SPRING_PROFILE_ACTIVE: "dev"
  # must match postgres Service name below
  DATASOURCE_HOST: "postgres-service"
  DATASOURCE_DBNAME: "notes-service"
  LOGGING_LEVEL_APP: "DEBUG"
  LOGGING_LEVEL_SPRING: "DEBUG"

  # --- postgres ---
  POSTGRES_DB: "notes-service"