apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: notes-app
  name: postgres-data
  labels:
    app: postgres
spec:
  accessModes:
    # ReadWriteOnce = only one node can mount this volume at a time
    # correct for single postgres instance
    - ReadWriteOnce
  resources:
    requests:
      # increase this for production
      storage: 1Gi