apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: notes-app
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  # Recreate = stop old pod before starting new one
  # important for stateful apps with PVC (only one pod can write at a time)
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            # non-sensitive config from ConfigMap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: notes-service-config
                  key: POSTGRES_DB
            # sensitive credentials from Secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: notes-service-secret
                  key: DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notes-service-secret
                  key: DATASOURCE_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata #fix for GCE postgres deployment
          # liveness probe — checks if postgres is accepting connections
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
      restartPolicy: Always