apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.service.name}}
  labels:
    {{- include "notes-service.labels" . | nindent 4}}
spec:
  # ClusterIP = internal only, accessible within cluster via DNS
  # notes-service-bff will reach this via http://notes-service:9004
  type: ClusterIP
  selector:
    {{- include "notes-service.selectorLabels" . | nindent 4}}
  ports:
    # main application port
    - name: http
      port: {{ .Values.service.mainPort }}
      targetPort: {{ .Values.service.mainPort }}
    # actuator port — for internal monitoring only
    - name: actuator
      port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}